spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/jobservice
    username: postgres
    password: mk123654
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        validator:
          apply_to_ddl: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 1f12a9f5bba8cfe83a23
            client-secret: 5ab7277b0bd2c84f5ca1b1dfc8857ba4c43006c1
            redirect-uri: http://localhost:8080/login/oauth2/code/github
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: name

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8080

